### ISSUE TITLE
NullSerializer.dumps missing 1 required positional argument 'value'

### ISSUE THREAD

**Issue by ibigpapa** [argaen/aiocache#480]
I'm attempting to use the in memory cache and null serializer but it fails to set a value.

```Python 3.8.0 (default, Oct 28 2019, 16:14:01) 
Type 'copyright', 'credits' or 'license' for more information
IPython 7.13.0 -- An enhanced Interactive Python. Type '?' for help.
PyDev console: using IPython 7.13.0
Python 3.8.0 (default, Oct 28 2019, 16:14:01) 
[GCC 8.3.0] on linux
import asyncio
loop = asyncio.get_event_loop()
from aiocache import Cache, SimpleMemoryCache
from aiocache.serializers import NullSerializer
cache = Cache(SimpleMemoryCache, serializer=NullSerializer)
loop.run_until_complete(cache.set('key', 'value'))```

Traceback:
```Traceback (most recent call last):
  File "/home/user/PycharmProjects/app/venv/lib/python3.8/site-packages/IPython/core/interactiveshell.py", line 3331, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-7-8853993daa49>", line 1, in <module>
    loop.run_until_complete(cache.set('key', 'value'))
  File "/usr/lib/python3.8/asyncio/base_events.py", line 608, in run_until_complete
    return future.result()
  File "/home/user/PycharmProjects/app/venv/lib/python3.8/site-packages/aiocache/base.py", line 61, in _enabled
    return await func(*args, **kwargs)
  File "/home/user/PycharmProjects/app/venv/lib/python3.8/site-packages/aiocache/base.py", line 45, in _timeout
    return await asyncio.wait_for(func(self, *args, **kwargs), timeout)
  File "/usr/lib/python3.8/asyncio/tasks.py", line 483, in wait_for
    return fut.result()
  File "/home/user/PycharmProjects/app/venv/lib/python3.8/site-packages/aiocache/base.py", line 75, in _plugins
    ret = await func(self, *args, **kwargs)
  File "/home/user/PycharmProjects/app/venv/lib/python3.8/site-packages/aiocache/base.py", line 265, in set
    ns_key, dumps(value), ttl=self._get_ttl(ttl), _cas_token=_cas_token, _conn=_conn
TypeError: dumps() missing 1 required positional argument: 'value'```

**Comment by ibigpapa** [comment]
i stepped through using a debugger and on `/home/user/PycharmProjects/app/venv/lib/python3.8/site-packages/aiocache/base.py` line # 265

validated that the value is available there and expected.  I also validated that the `dumps` function refers to the `/home/user/PycharmProjects/app/venv/lib/python3.8/site-packages/aiocache/base.py` line # 53

**Comment by paulo-raca** [comment]
You must use a serializer instance instead of a type:

`cache = Cache(SimpleMemoryCache, serializer=NullSerializer())`

**Comment by argaen** [comment]
that's right! Thanks @paulo-raca
