### ISSUE TITLE
Caching Pandas Data Frame

### ISSUE THREAD

**Issue by mpekalski** [argaen/aiocache#493]
I have a method that returns Pandas' DataFrame. It is quite expensive to compute, hence the cache. I use `Cache.MEMORY`. The problem is I am getting an error when the cache clears itself:

```
[ERROR] asyncio:382 Exception in callback <bound method SimpleMemoryBackend.__delete of <class 'aiocache.backends.memory.SimpleMemoryCache'>>
handle: <TimerHandle SimpleMemoryBackend.__delete>
Traceback (most recent call last):
  File "uvloop/cbhandles.pyx", line 265, in uvloop.loop.TimerHandle._run
  File ".local/share/virtualenvs/calculation-service-9S56WXHV/lib/python3.8/site-packages/aiocache/backends/memory.py", line 101, in __delete
    if cls._cache.pop(key, None):
  File ".local/share/virtualenvs/calculation-service-9S56WXHV/lib/python3.8/site-packages/pandas/core/generic.py", line 1478, in __nonzero__
    raise ValueError(
ValueError: The truth value of a DataFrame is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().
```

The problem is that `__delete` method does `pop()` from cache and assumes the popped item can be evaluated to boolean, which is not true for Pandas' DataFrame/Series. 

`aiocache/backends/memory.py`
```
    @classmethod
    def __delete(cls, key):
        if cls._cache.pop(key, None):
            handle = cls._handlers.pop(key, None)
            if handle:
                handle.cancel()
            return 1

        return 0
```

Minimal (not) working example

```
import asyncio
loop = asyncio.get_event_loop()
from aiocache import Cache
cache = Cache(Cache.MEMORY) # Here you can also use Cache.REDIS and Cache.MEMCACHED, default is Cache.MEMORY
loop.run_until_complete(cache.set("key", "value"))
loop.run_until_complete(cache.get("key"))

import pandas as pd

df = pd.DataFrame({"a":[123], "b":[456]})
loop.run_until_complete(cache.set("key2", df))
loop.run_until_complete(cache.get("key2"))
loop.run_until_complete(cache.delete("key2"))
```

**Comment by mpekalski** [comment]
Looks like it can be solved with a custom Serializer

```
import asyncio
loop = asyncio.get_event_loop()
from aiocache import Cache
cache = Cache(Cache.MEMORY) # Here you can also use Cache.REDIS and Cache.MEMCACHED, default is Cache.MEMORY
loop.run_until_complete(cache.set("key", "value"))
loop.run_until_complete(cache.get("key"))

import pandas as pd
from aiocache.serializers import BaseSerializer
import zlib
import pickle
class CompressionSerializer(BaseSerializer):

    # This is needed because zlib works with bytes.
    # this way the underlying backend knows how to
    # store/retrieve values
    DEFAULT_ENCODING = None

    def dumps(self, value):
        print("I've received:\n{}".format(value))
        compressed = zlib.compress(pickle.dumps(value))
        print("But I'm storing:\n{}".format(compressed))
        return compressed

    def loads(self, value):
        print("I've retrieved:\n{}".format(value))
        decompressed = pickle.loads(zlib.decompress(value))
        print("But I'm returning:\n{}".format(decompressed))
        return decompressed


cache = Cache(Cache.MEMORY, serializer=CompressionSerializer(), namespace="main")


df = pd.DataFrame({"a":[123], "b":[456]})
loop.run_until_complete(cache.set("key2", df))
loop.run_until_complete(cache.get("key2"))
loop.run_until_complete(cache.delete("key2"))
```
