### ISSUE TITLE
UnicodeDecodeError with PickleSerializer

### ISSUE THREAD

**Issue by maxxst** [argaen/aiocache#515]
I was trying to use the PickleSerializer in the following file:

```python
import asyncio

from collections import namedtuple

from aiocache import cached, Cache
from aiocache.serializers import PickleSerializer

Result = namedtuple('Result', "content, status")


@cached(
    ttl=10, cache=Cache.REDIS, key="key", serializer=PickleSerializer(),
    port=6379, namespace="main")
async def cached_call():
    return Result("content", 200)


async def test_cached():
    cache = Cache(Cache.REDIS, endpoint="127.0.0.1", port=6379, namespace="main")
    result = await cached_call()
    assert await cache.exists("key") is True
    test = await cache.get("key")
    print(test)
    await cache.delete("key")
    await cache.close()
    return result


if __name__ == "__main__":
    print(asyncio.run(test_cached()))
```

running it results in:

```
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x80 in position 0: invalid start byte
```

using JsonSerializer works fine.

Full Response Dump:

```
$ python test_aiocache.py
msgpack not installed, MsgPackSerializer unavailable
Traceback (most recent call last):
  File "test_aiocache.py", line 30, in <module>
    print(asyncio.run(test_cached()))
  File "/usr/local/Cellar/python@3.8/3.8.6/Frameworks/Python.framework/Versions/3.8/lib/python3.8/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/local/Cellar/python@3.8/3.8.6/Frameworks/Python.framework/Versions/3.8/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "test_aiocache.py", line 22, in test_cached
    test = await cache.get("key")
  File "/Users/max/.venv/wdsmt/lib/python3.8/site-packages/aiocache/base.py", line 61, in _enabled
    return await func(*args, **kwargs)
  File "/Users/max/.venv/wdsmt/lib/python3.8/site-packages/aiocache/base.py", line 45, in _timeout
    return await asyncio.wait_for(func(self, *args, **kwargs), timeout)
  File "/usr/local/Cellar/python@3.8/3.8.6/Frameworks/Python.framework/Versions/3.8/lib/python3.8/asyncio/tasks.py", line 491, in wait_for
    return fut.result()
  File "/Users/max/.venv/wdsmt/lib/python3.8/site-packages/aiocache/base.py", line 75, in _plugins
    ret = await func(self, *args, **kwargs)
  File "/Users/max/.venv/wdsmt/lib/python3.8/site-packages/aiocache/base.py", line 192, in get
    value = loads(await self._get(ns_key, encoding=self.serializer.encoding, _conn=_conn))
  File "/Users/max/.venv/wdsmt/lib/python3.8/site-packages/aiocache/backends/redis.py", line 24, in wrapper
    return await func(self, *args, _conn=_conn, **kwargs)
  File "/Users/max/.venv/wdsmt/lib/python3.8/site-packages/aiocache/backends/redis.py", line 102, in _get
    return await _conn.get(key, encoding=encoding)
  File "/Users/max/.venv/wdsmt/lib/python3.8/site-packages/aioredis/connection.py", line 234, in _process_data
    obj = decode(obj, encoding)
  File "/Users/max/.venv/wdsmt/lib/python3.8/site-packages/aioredis/util.py", line 45, in decode
    return obj.decode(encoding)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x80 in position 0: invalid start byte
```

**Comment by prochanev-thw** [comment]
Hi @maxxst! What was it? I have the same problem.

**Comment by maxxst** [comment]
If I remember correctly:
I had a non serialized entry in my cache and then the unpickle of that entry would fail.

For me it was a test entry from before I started serializing. Deleting that entry fixed it.
