### ISSUE TITLE
Check compatibility with curio

### ISSUE THREAD

**Issue by argaen** [argaen/aiocache#74]
Seems async-timeout is not compatible:

1. 
```python
Traceback (most recent call last):
  File "/home/blck/.pyenv/versions/aiocache/lib/python3.5/site-packages/curio/kernel.py", line 531, in run
    trap = current._send(current.next_value)
  File "/home/blck/Projects/aiocache/aiocache/plugins.py", line 14, in wrapper
    ret = await func(self, *args, **kwargs)
  File "/home/blck/Projects/aiocache/aiocache/cache.py", line 210, in delete
    with Timeout(self._timeout):
  File "/home/blck/.pyenv/versions/aiocache/lib/python3.5/site-packages/async_timeout/__init__.py", line 33, in __enter__
    raise RuntimeError('Timeout context manager should be used '
RuntimeError: Timeout context manager should be used inside a task
```
need to find a way to add timeouts compatible with both frameworks

2. Also seems there is another error
```python
2016-11-28 23:04:17,694 ERROR curio.kernel(554) | Curio: Task Crash: redis
Traceback (most recent call last):
  File "/home/blck/.pyenv/versions/aiocache/lib/python3.5/site-packages/curio/kernel.py", line 537, in run
    traps[trap[0]](*trap)
TypeError: 'Future' object does not support indexing
2016-11-28 23:04:17,695 ERROR curio.kernel(554) | Curio: Task Crash: plugin_pipeline.<locals>.wrapper
Traceback (most recent call last):
  File "/home/blck/.pyenv/versions/aiocache/lib/python3.5/site-packages/curio/kernel.py", line 537, in run
    traps[trap[0]](*trap)
TypeError: 'Future' object does not support indexing
2016-11-28 23:04:17,695 ERROR curio.kernel(554) | Curio: Task Crash: plugin_pipeline.<locals>.wrapper
Traceback (most recent call last):
  File "/home/blck/.pyenv/versions/aiocache/lib/python3.5/site-packages/curio/kernel.py", line 537, in run
    traps[trap[0]](*trap)
TypeError: 'Future' object does not support indexing
```

**Comment by argaen** [comment]
For the time being there are a couple of reasons why there can't be compatibility:

- we are using `asyncio.wait_for` for timing out operations which is `asyncio` specific. curio doesn't support it.
- aioredis and aiomcache are asyncio specific. The only backend that would work would be SimpleMemoryCache (and without ttls because its using `call_later`...).
